- name: aristotle
  hosts: aristotle

  roles:
    - ssh
    - { role: ufw, become: yes }
    - { role: certbot, become: yes }
    - { role: nginx, become: yes }
    - { role: albatross, become: yes }
    - redis
