- name: brunelli
  hosts: brunelli
  vars:
    nginx_server_name: "brunelli"
    ansible_python_interpreter: /usr/bin/python3

  roles:
    # - ssh
    - zsh
    - { role: ufw, become: yes }
    - tmux
    - nvim
    - go
    - { role: certbot, become: yes }
    - { role: nginx, become: yes }
