#!/bin/bash

source "$HOME/dotfiles/sketchybar/colors.sh"
source "$HOME/dotfiles/sketchybar/icons.sh"

ITEM_DIR="$HOME/dotfiles/sketchybar/items"
PLUGIN_DIR="$HOME/dotfiles/sketchybar/plugins"

FONT="Comic Mono"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32            \
                 blur_radius=50       \
                 position=top         \
                 sticky=true          \
                 padding_left=10      \
                 padding_right=10     \
                 margin=10            \
                 y_offset=10          \
                 corner_radius=7      \
                 color=$BACKGROUND_1

sketchybar --default updates=when_shown                    \
                     drawing=on                            \
                     icon.font="$FONT:Bold:14.0"  \
                     icon.color=0xffffffff                 \
                     label.font="$FONT:Bold:14.0" \
                     label.color=0xffffffff                \
                     label.padding_left=4                  \
                     label.padding_right=4                 \
                     icon.padding_left=4                   \
                     icon.padding_right=4

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# Left Items
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

# source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/spotify.sh"

# Right Items
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/date.sh"
source "$ITEM_DIR/clock.sh"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration and
# should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
