- name: Install flavours
  community.general.homebrew:
    name: flavours
    state: present
- name: Sync configs
  ansible.builtin.include_role:
    name: env
    tasks_from: linkConfig
  vars:
    config_dir: "{{ ansible_env.HOME }}/.config/flavours/base16"
