[shell]
program = "/bin/zsh"

# Start flavours
# Base16 scheme01 - alacritty color config
# terminalPoltergeist

[colors.primary]
  # Default colors
  background = '#121212'
  foreground = '#c1c1c1'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
  text = '#c1c1c1'
  cursor = '#a06666'

[colors.normal]
  black = '#121212'
  red = '#a06666'
  green = '#5f8766'
  yellow = '#ddb699'
  blue = '#5f87a9'
  magenta = '#8477a4'
  cyan = '#5f8787'
  white = '#c1c1c1'

[colors.bright]
  black = '#333333'
  red = '#a06666'
  green = '#5f8766'
  yellow = '#ddb699'
  blue = '#5f87a9'
  magenta = '#8477a4'
  cyan = '#5f8787'
  white = '#c1c1c1'


# End flavours

[font]
size = 11.5

[font.bold]
family = "Comic Code"
style = "Bold"

[font.bold_italic]
family = "Comic Code"
style = "Bold Italic"

[font.italic]
family = "Comic Code"
style = "Medium Italic"

[font.normal]
family = "Comic Code"
style = "Medium"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 1

[window.padding]
x = 20
y = 20
