- name: "Config for Ubuntu22"
  ansible.builtin.include_tasks: ubuntu22.yml
  when: ansible_os_family == "Debian"
- name: "Config for Fedora39"
  ansible.builtin.include_tasks: fedora39.yml
  when: ansible_os_family == "RedHat"
