- name: Place systemd service file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/albatross.service"
    dest: "/etc/systemd/system/albatross.service"
    mode: '0644'
  register: albatross

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: albatross.changed

- name: Check for log file
  ansible.builtin.shell: test -f /var/log/albatross.log
  register: log
  changed_when: false
  ignore_errors: true

- name: Create log file
  ansible.builtin.file:
    path: "/var/log/albatross.log"
    state: touch
    mode: '0644'
    owner: jack
  when: log.failed

- name: Enable albatross service
  ansible.builtin.systemd:
    name: albatross
    enabled: true
    state: started
