---
- name: "Setup go for x86"
  ansible.builtin.include_tasks: x86.yml
  when: ansible_architecture == "x86_64"

- name: "Setup go for arm"
  ansible.builtin.include_tasks: arm.yml
  when: ansible_architecture == "arm"
