# Commands go through bash
shell = "bash -c '{}'"

[[item]]
file = "/Users/jacknemitz/.config/alacritty/alacritty.toml"
template = "alacritty"

[[item]]
file = "/Users/jacknemitz/.config/nvim/lua/terminalPoltergeist/colors.lua"
template = "nvim"
subtemplate = "custom"
start = "-- Start flavours"
end = "-- End flavours"

[[item]]
file = "/Users/jacknemitz/.tmux.conf"
template = "tmux"
subtemplate = "base16"
hook = "tmux source ~/.tmux.conf"
start = "# Start flavours"
end = "# End flavours"

[[item]]
file = "/Users/jacknemitz/.config/spicetify/Themes/Custom/color.ini"
template = "spicetify"
# subtemplate = "default"
start = "# Start flavours"
end = "# End flavours"
rewrite = true

[[item]]
file = "/Users/jacknemitz/.zshrc"
template = "zsh"
start = "# Start flavours"
end = "# End flavours"

[[item]]
file = "/Users/jacknemitz/.config/bat/config"
template = "bat"
start = "# Start flavours"
end = "# End flavours"
