# Commands go through bash
shell = "bash -c '{}'"

[[item]]
file = "/Users/jacknemitz/.config/alacritty/alacritty.toml"
template = "alacritty"
subtemplate = "custom"

# [[item]]
# file = "/Users/jacknemitz/dotfiles/nvim/init.vim"
# template = "vim"
# start = "\" Start flavours"
# end = "\" End flavours"

[[item]]
file = "/Users/jacknemitz/.config/nvim/lua/init.lua"
template = "nvim"
start = "-- Start flavours"
end = "-- End flavours"

[[item]]
file = "/Users/jacknemitz/.tmux.conf"
template = "tmux"

[[item]]
file = "/Users/jacknemitz/.config/spicetify/Themes/Custom/color.ini"
template = "spicetify"
# subtemplate = "default"
start = "# Start flavours"
end = "# End flavours"
rewrite = true

[[item]]
file = "/Users/jacknemitz/dotfiles/sketchybar/colors.sh"
template = "sketchybar"
start = "# Start flavours"
end = "# End flavours"
rewrite = true

[[item]]
file = "/Users/jacknemitz/Desktop/projects/jacknemitz.com/tailwind.config.js"
template = "jacknemitz.com"
start = "// Start flavours"
end = "// End flavours"

[[item]]
file = "/Users/jacknemitz/.zshrc"
template = "zsh"
start = "# Start flavours"
end = "# End flavours"
