- name: Add Docker GPG key to apt
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install pip3
  ansible.builtin.apt:
    name: "python3-pip"
    state: present

- name: Install python Docker module
  ansible.builtin.pip:
    name: docker
