- name: Install alacritty
  community.general.homebrew:
    name: alacritty
    state: present
- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: '0755'
- name: Sync configs
  ansible.builtin.include_role:
    name: env
    tasks_from: linkConfig
  vars:
    config_dir: "{{ ansible_env.HOME }}/.config/alacritty"
# - name: Link configs
#   ansible.builtin.file:
#     src: "{{ role_path }}/files"
#     dest: "{{ ansible_env.HOME }}/.config/nvim/lua"
#     state: link
#     force: true
