# - name: Detect zsh
#   ansible.builtin.shell: which zsh
#   register: zsh
#   changed_when: false
#   ignore_errors: true
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: Get zsh path
  ansible.builtin.shell: which zsh
  register: zsh
  changed_when: false

- name: Copy configs
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_env.HOME }}/.config/zsh"
    owner: "{{ ansible_user_id }}"
    mode: '0755'
  when: dev_machine is undefined or not dev_machine

- name: Link configs
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_env.HOME }}/.config/zsh"
    state: link
    force: true
  when: dev_machine is defined and dev_machine

- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true

- name: Remove local source command
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: 'source \$HOME/dotfiles/path'
    state: absent

- name: Set shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
  become: true
