name: Sync systems
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  aristotle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      dns_api_key: ${{secrets.CLOUDFLARE_DNS_API_KEY}}
      vault_psswd: ${{secrets.VAULT_PASS}}
      become_psswd: ${{secrets.BECOME_PASS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      ARISTOTLE_IP: ${{secrets.ARISTOTLE_IP}}
      ARISTOTLE_PORT: ${{secrets.ARISTOTLE_PORT}}
      ANSIBLE_STDOUT_CALLBACK: "junit"
      JUNIT_OUTPUT_DIR: "~/junit-results"
    steps:
      - uses: actions/checkout@v3
      - name: install junit for python
        run: sudo apt install python3-junit.xml
      - name: configure ssh
        run: |
          mkdir ~/.ssh
          # touch ~/.ssh/known_hosts
          # chmod 0600 ~/.ssh/known_hosts
          # echo "$ARISTOTLE_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          ssh-keyscan -p $ARISTOTLE_PORT -H $ARISTOTLE_IP >> ~/.ssh/known_hosts
          echo "$SSH_KEY" >> ~/.ssh/id_rsa_homeLab
          chmod 0600 ~/.ssh/id_rsa_homeLab
      - name: run playbook
        shell: bash
        run: |
          ansible-playbook --private-key="$SSH_KEY" --user="jack" aristotle.yml -i homelab.yml -e ansible_sudo_pass=$become_psswd -e dns_cloudflare_api_token=$dns_api_key --vault-password-file=<(echo $vault_psswd)
      - name: publish run
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Junit results
          path: ~/junit-results/*.xml
          reporter: java-junit
          fail-on-error: true
  brunelli:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      dns_api_key: ${{secrets.CLOUDFLARE_DNS_API_KEY}}
      vault_psswd: ${{secrets.VAULT_PASS}}
      become_psswd: ${{secrets.BECOME_PASS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
      BRUNELLI_IP: ${{secrets.BRUNELLI_IP}}
      BRUNELLI_PORT: ${{secrets.BRUNELLI_PORT}}
      ANSIBLE_STDOUT_CALLBACK: "junit"
      JUNIT_OUTPUT_DIR: "~/junit-results"
    steps:
      - uses: actions/checkout@v3
      - name: install junit for python
        run: sudo apt install python3-junit.xml
      - name: configure ssh
        run: |
          mkdir ~/.ssh
          # touch ~/.ssh/known_hosts
          # chmod 0600 ~/.ssh/known_hosts
          # echo "$BRUNELLI_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          ssh-keyscan -p $BRUNELLI_PORT -H $BRUNELLI_IP >> ~/.ssh/known_hosts
          echo "$SSH_KEY" >> ~/.ssh/id_rsa_homeLab
          chmod 0600 ~/.ssh/id_rsa_homeLab
      - name: run playbook
        shell: bash
        run: |
          ansible-playbook --private-key="$SSH_KEY" --user="jack" brunelli.yml -i homelab.yml -e ansible_sudo_pass=$become_psswd -e dns_cloudflare_api_token=$dns_api_key --vault-password-file=<(echo $vault_psswd)
      - name: publish run
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Junit results
          path: ~/junit-results/*.xml
          reporter: java-junit
          fail-on-error: true

