name: Sync systems
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  aristotle:
    runs-on: ubuntu-latest
    env:
      dns_api_key: ${{secrets.CLOUDFLARE_DNS_API_KEY}}
      vault_psswd: ${{secrets.VAULT_PASS}}
      become_psswd: ${{secrets.BECOME_PASS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
      - uses: actions/checkout@v3
      - name: configure ssh
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" >> ~/.ssh/github_actions
          chmod 0600 ~/.ssh/github_actions
      - name: run playbook
        shell: bash
        run: |
          ansible-playbook --private-key="$SSH_KEY" --user="jack" aristotle.yml -i homelab.yml -e ansible_sudo_pass=$become_psswd -e dns_cloudflare_api_token=$dns_api_key --vault-password-file=<(echo $vault_psswd)
  brunelli:
    runs-on: ubuntu-latest
    env:
      dns_api_key: ${{secrets.CLOUDFLARE_DNS_API_KEY}}
      vault_psswd: ${{secrets.VAULT_PASS}}
      become_psswd: ${{secrets.BECOME_PASS}}
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
      - uses: actions/checkout@v3
      - name: configure ssh
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" >> ~/.ssh/github_actions
          chmod 0600 ~/.ssh/github_actions
      - name: run playbook
        shell: bash
        run: |
          ansible-playbook --private-key="$SSH_KEY" --user="jack" brunelli.yml -i homelab.yml -e ansible_sudo_pass=$become_psswd -e dns_cloudflare_api_token=$dns_api_key --vault-password-file=<(echo $vault_psswd)
